### ISSUE TITLE
Freezing after initial drag event on Samsung devices

### ISSUE THREAD

**Issue by arjs1000** [kikoso/Swipeable-Cards#21]
Hi there, 

I am in the process of developing this functionality into an Android App. However, I noticed that there is a view layout update problem for cards when you stop dragging on Samsung devices. The Card resets and freezes in position, thus no longer being responsive to touch events.

Tested on Samsung Galaxy S3 and Samsung S3 mini (version 4.1.2).

I have modified the library to use the Picasso image library as such:

public class VenueCardAdapter extends CardStackAdapter implements VenueCardModel.OnCardDimissedListener {

```
private ArrayList<Venue> vList;
private Context vCon;
private int count = 0;

    public VenueCardAdapter(Context mContext, ArrayList<Venue> theVenues)
    {
        super(mContext);
        vCon = mContext;
        vList = theVenues;
        count = 0;
    }

public static class ViewHolder {

    public TextView tvVenueName;
    public TextView tvVenueAbout = null;
    public ImageView ivVenueImage = null;
    public RatingBar venueRating;

}


@Override
    public View getCardView(int position, CardModel model, View convertView, ViewGroup parent) {
        final ViewHolder holder;
        if(convertView == null) {

            holder = new ViewHolder();

            LayoutInflater inflater = LayoutInflater.from(getContext());
            convertView = inflater.inflate(com.andtinder.R.layout.std_card_inner, parent, false);
            if(convertView!=null) {
                holder.tvVenueName = (TextView) convertView.findViewById(com.andtinder.R.id.title);
                holder.tvVenueAbout = (TextView) convertView.findViewById(com.andtinder.R.id.about);
                holder.ivVenueImage = (ImageView) convertView.findViewById(com.andtinder.R.id.image);
                holder.venueRating = (RatingBar) convertView.findViewById(com.andtinder.R.id.rating);
                holder.venueRating.setEnabled(false);
            }
            assert convertView != null;
            convertView.setTag(holder);
        }
        else
            holder=(ViewHolder)convertView.getTag();

        if(holder != null) {

            // ensures only latest top 3 cards are loaded

                final Venue theVenue = vList.get(position);

                if (theVenue != null) {

                    String about = "";
                    String address = theVenue.address1;
                    if (address == null) {
                        address = "";
                    } else {
                        // trim to only 25 chars or less
                        if (address.length() >= 25) {
                            address = address.substring(0, 25) + "..";
                        }

                    }

                    String distance = "";
                    if (theVenue.distance != null) {
                        distance = theVenue.distance.substring(0, 4) + " mi";
                    }
                    about = address + " | " + distance;



                    if (theVenue.images != null) {
                        String imageNo = theVenue.images[0];
                        String url = "http://api.paywithvelocity.com/1/image?fileID=" + imageNo;
                        if (Config.DOWNLOAD_IMAGES) {

                            // ensures only latest top 3 card images are downloaded
                            if (position >= count && position < (count + 3)) {
                            Picasso.with(vCon).load(url).resize((int) (parent.getMeasuredWidth()), parent.getMeasuredHeight()).centerInside()
                                    .placeholder(R.drawable.placeholder_image).into(holder.ivVenueImage);
                            } // Top 3 cards
                        } else {

                            Picasso.with(vCon).load(R.drawable.placeholder_image).into(holder.ivVenueImage);

                        }
                    } else {

                        Picasso.with(vCon).load(R.drawable.placeholder_image).into(holder.ivVenueImage);

                    }

                    if(holder.tvVenueName !=null) {
                        if(theVenue.venueName != null) {
                            String name = theVenue.venueName;

                            if(name.length() >= 15)
                            {
                                name = name.substring(0,15) + ".. ";
                            }

                                holder.tvVenueName.setText(name);
                        }
                    }
                    if(holder.tvVenueAbout != null) {
                        holder.tvVenueAbout.setText(about);
                    }


                } // Venue not null



        } // holder not null
        return convertView;
    }

/// Actually Dislike!
@Override
public void onLike() {
    if(count < vList.size()) {
        super.pop();
        Venue onTop = vList.get(count);

        Toast.makeText(vCon, "You disliked " + onTop.venueName + "!", Toast.LENGTH_SHORT).show();
        count++;

    }
}



// Actually Like!
@Override
public void onDislike() {
    if(count < vList.size()) {
        super.pop();
        Venue onTop = vList.get(count);

        Toast.makeText(vCon, "You liked " + onTop.venueName + "!", Toast.LENGTH_SHORT).show();
        count++;

        Intent openBooking = new Intent(vCon, BookingActivity.class);

        openBooking.putExtra("venueName", ""+onTop.venueName);

        vCon.startActivity(openBooking);


    }
}
```

}

**Comment by BKerestan** [comment]
Your description of the problem sounds a lot like the behavior I encountered trying to implement an endless adapter. You can see my reply to the "Endless adapter" thread for the long winded full explanation of what I did, but I'll TL;DR it here.

When I would try to update the adapter by adding new cards to the stack, it would reset and freeze whenever the new card was added. This seemed to be caused by the call to NotifyDataSetChanged() in the CardStackAdapter's add method. I created a duplicate method by a different name that was identical, but did not have the NotifyDataSetChanged() call. When I did this (only tested with a low mMaxVisible value and number of cards > mMaxVisible), any cards added dynamically were added by calling the method that did not include NotifyDataSetChanged. That solved the issue for me.

**Comment by sirajsumra92** [comment]
@BKerestan I am getting these issue with the Library while testing on Samsung Galaxy Core on Intercept Touch Event:

04-13 17:28:05.252: E/AndroidRuntime(2549): java.lang.IllegalArgumentException: pointerIndex out of range
04-13 17:28:05.252: E/AndroidRuntime(2549): at android.view.MotionEvent.nativeGetAxisValue(Native Method)
04-13 17:28:05.252: E/AndroidRuntime(2549): at android.view.MotionEvent.getX(MotionEvent.java:2145)

Getting issue in Intercept Touch Event in following code in container:
case MotionEvent.ACTION_MOVE:
pointerIndex = event.findPointerIndex(mActivePointerId);
x = event.getX(pointerIndex);
y = event.getY(pointerIndex);

Can u please help me with these issue.

**Comment by KonradJanica** [comment]
This is a helpful function I implemented to solve this problem:
``` java
    public void refreshTopCard() {
        ensureFull();
        if (getChildCount() != 0) {
            mTopCard = getChildAt(getChildCount() - 1);
            if (mTopCard != null)
                mTopCard.setLayerType(LAYER_TYPE_HARDWARE, null);
            mNumberOfCards = getAdapter().getCount();
        }
    }
```
Put this in CardContainer.java.
Note: I reversed ordering of cards before, can't remember if I altered this function too, if it doesn't work for you then change this line(3):
` mTopCard = getChildAt(0);`
