### ISSUE TITLE
Touch position problem

### ISSUE THREAD

**Issue by githubfan12221030** [kikoso/Swipeable-Cards#23]
Thanks for your good library.
I have installed the demo app on LG Vega phone.
When I touch the right bottom of card, it is not moving.

The event.getX() is 320 , and event.getY() is 456.
But the childRect that is get by getHitRect() function is (-172,-22)-(199, 349) even I click inside the card.

Help me!

And can you add the callback when the card is started moving to left or right?

**Comment by catalinv** [comment]
It looks like hitRect() method had a bug prior to Android 4.3 - More details on this thread : http://stackoverflow.com/questions/17750116/strange-view-gethitrect-behaviour
And helper method that should be used in CardContainer:

private static void getHitRect(View v, Rect rect) {
      rect.left = (int) (v.getLeft() + v.getTranslationX());
      rect.top = (int) (v.getTop() + v.getTranslationY());
      rect.right = rect.left + v.getWidth();
      rect.bottom = rect.top + v.getHeight();
  }

**Comment by mindnervestech** [comment]
this works for me thanks catalinv

**Comment by sirajsumra92** [comment]
catalinv I am getting these issue with the Library while testing on Samsung Galaxy Core on Intercept Touch Event:

04-13 17:28:05.252: E/AndroidRuntime(2549): java.lang.IllegalArgumentException: pointerIndex out of range
04-13 17:28:05.252: E/AndroidRuntime(2549): 	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
04-13 17:28:05.252: E/AndroidRuntime(2549): 	at android.view.MotionEvent.getX(MotionEvent.java:2145)

Getting issue in Intercept Touch Event in following code in container:
case MotionEvent.ACTION_MOVE:
			pointerIndex = event.findPointerIndex(mActivePointerId);
			x = event.getX(pointerIndex);
			y = event.getY(pointerIndex);

Can u please help me with these issue.

**Comment by mudar** [comment]
Hi @kikoso,
first of all, thanks a lot for this library!

Looking at the `pointerIndex` issue, could it be related to this?
http://developer.android.com/intl/es/reference/android/view/MotionEvent.html#getActionIndex()
> `getActionIndex ()`
> For ACTION_POINTER_DOWN or ACTION_POINTER_UP as returned by getActionMasked()

In `CardContainer onTouchEvent()`, there are 2 calls for `event.getActionIndex()`:
1.`case MotionEvent.ACTION_DOWN`: error?
2.`case MotionEvent.ACTION_POINTER_UP`: follows sdk documentation

**Comment by monishagarwal215** [comment]
Thanks @catalinv it worked for me.
I faced issue in 4.2.2. And by replacing by this method.

private static void getHitRect(View v, Rect rect) {
rect.left = (int) (v.getLeft() + v.getTranslationX());
rect.top = (int) (v.getTop() + v.getTranslationY());
rect.right = rect.left + v.getWidth();
rect.bottom = rect.top + v.getHeight();
}

It worked for me.
