### ISSUE TITLE
Performance issues (lag) in cell phones with better resolution

### ISSUE THREAD

**Issue by holic-cl** [kikoso/Swipeable-Cards#27]
Hi, i tested this library on different devices and i got worst performance in the ones that have better resolution.

The devices i tested are Samsung S4 Mini, Samsung S4, Motorola Moto X 1st Generation, Motorola Moto X 2nd Generation, and Samsung S5. Most laggy one was Motorola Moto X 2nd Generation, but it works laggy in everyone except in Samsung S4 Mini and Motorola Moto X 1st Gen.

If you have some way to deal with this, i will appreciate.

Regards.

**Comment by sirajsumra92** [comment]
H0LiC I am getting these issue with the Library while testing on Samsung Galaxy Core on Intercept Touch Event:

04-13 17:28:05.252: E/AndroidRuntime(2549): java.lang.IllegalArgumentException: pointerIndex out of range
04-13 17:28:05.252: E/AndroidRuntime(2549): 	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
04-13 17:28:05.252: E/AndroidRuntime(2549): 	at android.view.MotionEvent.getX(MotionEvent.java:2145)

Seems Similar with your Issue, I tried your solution but still Illegal Argument Exception. Did you came up with the better Solution?

**Comment by H0LiC** [comment]
Nope, and it seems this library is not maintained by the owner.

The only recommendation i can give you is to use this library instead:
https://github.com/Diolor/Swipecards

regards
