### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by vipulasri** [kikoso/Swipeable-Cards#73]
I having this error : 

<code>
java.lang.UnsupportedOperationException
            at com.andtinder.view.CardContainer.getSelectedView(CardContainer.java:387)
            at android.widget.AdapterView.onInitializeAccessibilityEvent(AdapterView.java:972)
            at android.widget.AdapterView.onRequestSendAccessibilityEvent(AdapterView.java:947)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:739)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:743)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:743)
            at android.view.ViewGroup.requestSendAccessibilityEvent(ViewGroup.java:743)
            at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5318)
            at android.view.View.sendAccessibilityEventUnchecked(View.java:5299)
            at android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:21009)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
</code>

**Comment by ImranAtArbisoft** [comment]
Same here

**Comment by vipulasri** [comment]
@ImranAtArbisoft I got it solved by changing :  

    @Override
    public View getSelectedView() {
    throws UnsupportedOperationException;
    }
to

    @Override
    public View getSelectedView() {
    return mTopCard;
    }

in <code>CardContainer.java</code>.
You might have to manually import all the files in library in your project.

**Comment by priyansh360** [comment]
compile 'com.github.kikoso:SwipeableCards:1.1-RELEASE@aar'

**Comment by priyansh360** [comment]
How To Change Data in CardContainer.java
