### ISSUE TITLE
Jacoco Error FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by rascyber** [kikoso/Swipeable-Cards#90]
Hi I am having this issue when trying to run the code to Nexus 6P. Please see the error log, perhaps you can help to resolve. 

Shutting down VM
02-21 06:40:29.811 3133-3133/com.andtinder.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.andtinder.demo, PID: 3133
                                                                  java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_773e439/Offline;
                                                                      at com.andtinder.view.CardContainer.$jacocoInit(CardContainer.java)
                                                                      at com.andtinder.view.CardContainer.<clinit>(CardContainer.java)
                                                                      at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                      at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
                                                                      at android.app.Activity.setContentView(Activity.java:2172)
                                                                      at com.andtinder.demo.MainActivity.onCreate(MainActivity.java:42)
                                                                      at android.app.Activity.performCreate(Activity.java:6251)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                   Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_773e439.Offline" on path: DexPathList[[zip file "/data/app/com.andtinder.demo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.andtinder.demo-2/lib/arm64, /vendor/lib64, /system/lib64]]
                                                                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                      at com.andtinder.view.CardContainer.$jacocoInit(CardContainer.java) 
                                                                      at com.andtinder.view.CardContainer.<clinit>(CardContainer.java) 
                                                                      at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                      at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393) 
                                                                      at android.app.Activity.setContentView(Activity.java:2172) 
                                                                      at com.andtinder.demo.MainActivity.onCreate(MainActivity.java:42) 
                                                                      at android.app.Activity.performCreate(Activity.java:6251) 
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                  	Suppressed: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_773e439.Offline
                                                                      at java.lang.Class.classForName(Native Method)
                                                                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                      		... 27 more
                                                                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by kikoso** [comment]
Is solved now

**Comment by rascyber** [comment]
I recloned the repo and now i'm getting this error.

Error:Could not find com.android.tools.build:gradle:2.0.0-beta2.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle/2.0.0-beta2/gradle-2.0.0-beta2.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle/2.0.0-beta2/gradle-2.0.0-beta2.jar
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.0.0-beta2/gradle-2.0.0-beta2.pom
    https://repo1.maven.org/maven2/com/android/tools/build/gradle/2.0.0-beta2/gradle-2.0.0-beta2.jar
Required by:
    :Swipeable-Cards:unspecified

**Comment by rascyber** [comment]
Now it run thanks. how to loop the cards so that user doesn't see blank screen after swiping all the cards?
